### ISSUE TITLE
Dep use older version of this code because of the tag v1

### ISSUE THREAD

**Issue by shackra** [dchest/authcookie#2]
`dep` clones `github.com/dchest/passwordreset` and fetch the dependencies for it which is this package, however, because of the incorrect tagging the oldest tag `v1` is use as reference point.

**Comment by meowgorithm** [comment]
+1. I've dealt with this a few times with dep and I'd assume this is the case with Go 1.11 modules as well.

P.S. @dchest: Like much of your other work, this is a fab library I keep coming back to!

**Comment by dchest** [comment]
Thank you! I removed all the tags, will it work well now (I'm kinda late for new go package management adoption).

**Comment by meowgorithm** [comment]
It should work now. @shackra, can you confirm?

The general practice with `dep` and `go mod` is something along the lines of v1.0.0 (aka semver), so if you were to tag it as such that would work too.

**Comment by shackra** [comment]
This should do it, dep will just fetch the latest commit of master.
